To-do-list: Add and Remove task from To-do-List
abiola-arobieke/to-do-list pull request #3
Opened 2023-04-07 20:14 UTC by abiola-arobieke

In this milestone:

The UI design was parsed.
Index.js, Index.html, and index.css files were updated.
Methods for performing a basic CRUD were added to the project.
Data were fetched dynamically and saved in the local storage.
Data were updated and saved dynamically in the local storage on adding, editing, or deleting a task.

2023-04-07 21:02 UTC, Mihndim2020 requested changes
### Hi @abiola-arobieke, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Clean and Organized code
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Since it is not a requirement for this project and you have not deployed the project, it will be nice to delete the `live demo section`.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 23:23 UTC, abiola-arobieke commented on src/index.js
> +    localStorage.setItem('allTask', JSON.stringify(task));
Please I don't understand. The data were updated and saved in the local storage after editing. You will need to press enter once you are done with the editing.

2023-04-08 09:55 UTC, prolajumokeoni commented on src/index.js
> +    localStorage.setItem('allTask', JSON.stringify(task));
This is currently fixe when I edit a task it if updated in the local storage 👍🏿

2023-04-08 09:57 UTC, prolajumokeoni approved these changes
Hi @abiola-arobieke 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
  - All changes requested have been implemented 🥇  
  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-09 02:09 UTC, merged